# Generated by Django 4.2.7 on 2026-02-28 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0003_bookmark_placecategory_placephoto_reviewvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'user_search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_search_user_id_c70f8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=20)),
                ('sentiment_score', models.FloatField()),
                ('quality_score', models.FloatField()),
                ('is_spam', models.BooleanField(default=False)),
                ('keywords', models.JSONField(default=list)),
                ('helpful_reason', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='places.review')),
            ],
            options={
                'verbose_name': 'Review AI Analysis',
                'verbose_name_plural': 'Review AI Analyses',
                'db_table': 'review_ai_analyses',
                'indexes': [models.Index(fields=['quality_score'], name='review_ai_a_quality_f22868_idx'), models.Index(fields=['is_spam'], name='review_ai_a_is_spam_a03d1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaceAISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=20)),
                ('positive_percentage', models.FloatField(default=0)),
                ('negative_percentage', models.FloatField(default=0)),
                ('neutral_percentage', models.FloatField(default=0)),
                ('top_keywords', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('concerns', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('review_count_at_generation', models.IntegerField()),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='places.place')),
            ],
            options={
                'verbose_name': 'Place AI Summary',
                'verbose_name_plural': 'Place AI Summaries',
                'db_table': 'place_ai_summaries',
                'indexes': [models.Index(fields=['-generated_at'], name='place_ai_su_generat_97257c_idx')],
            },
        ),
    ]
