# Generated by Django 4.2.7 on 2026-03-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_bookmark_placecategory_placephoto_reviewvote_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'place'), name='unique_user_place_bookmark'),
        ),
    ]
