# Generated by Django 4.2.7 on 2025-12-26 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='places_name_a0ffcc_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['-created_at'], name='places_created_ca2f1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_place_name_address'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['place', 'user'], name='reviews_place_i_a0f34e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['place', '-created_at'], name='reviews_place_i_1c1266_idx'),
        ),
    ]
